---
- name: Install ddclient
  apt:
    name: [ 'ddclient', 'policykit-1' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes

- name: Generiere /etc/ddclient.conf
  template:
    src: "ddclient/ddclient.conf.j2"
    dest: "/etc/ddclient.conf"
    owner: root
    group: root
    mode: '0600'
  become: yes